spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    # password: 123456
  h2:
    console:
      enabled: true
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。默认为/h2-console
      path: /h2
      # 控制h2 web consloe是否支持在远程访问。false只能在本机访问。
      settings:
        web-allow-others: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
mybatis:
  mapper-locations: classpath*:/mapper/*.xml